// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo3Yuw4QpCeXTM0xcCCrpPBbLeMKYDUEQ',
    appId: '1:324540492115:web:7836875b49a251f8ef19a6',
    messagingSenderId: '324540492115',
    projectId: 'chimay-house',
    authDomain: 'chimay-house.firebaseapp.com',
    storageBucket: 'chimay-house.firebasestorage.app',
    measurementId: 'G-2MZ6P52T7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2ONDsb7cm_09zxTToEYbo2PdooJrIBc',
    appId: '1:324540492115:android:8e9ed0af99c07177ef19a6',
    messagingSenderId: '324540492115',
    projectId: 'chimay-house',
    storageBucket: 'chimay-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEnPsZvi4tG_7K1nsfg5VoQ9Zh1sLKhNM',
    appId: '1:324540492115:ios:d46a4765f7958012ef19a6',
    messagingSenderId: '324540492115',
    projectId: 'chimay-house',
    storageBucket: 'chimay-house.firebasestorage.app',
    iosBundleId: 'com.example.chimayHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEnPsZvi4tG_7K1nsfg5VoQ9Zh1sLKhNM',
    appId: '1:324540492115:ios:d46a4765f7958012ef19a6',
    messagingSenderId: '324540492115',
    projectId: 'chimay-house',
    storageBucket: 'chimay-house.firebasestorage.app',
    iosBundleId: 'com.example.chimayHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo3Yuw4QpCeXTM0xcCCrpPBbLeMKYDUEQ',
    appId: '1:324540492115:web:90b89e07f06988b2ef19a6',
    messagingSenderId: '324540492115',
    projectId: 'chimay-house',
    authDomain: 'chimay-house.firebaseapp.com',
    storageBucket: 'chimay-house.firebasestorage.app',
    measurementId: 'G-XJ4NKMLPHY',
  );
}
